######################################################################################################
# ███████╗░█████╗░░██████╗████████╗███████╗██████╗░░█████╗░░██████╗░█████╗░███████╗███╗░░██╗██████╗░ #
# ██╔════╝██╔══██╗██╔════╝╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔════╝████╗░██║██╔══██╗ #
# █████╗░░███████║╚█████╗░░░░██║░░░█████╗░░██████╔╝███████║╚█████╗░██║░░╚═╝█████╗░░██╔██╗██║██║░░██║ #
# ██╔══╝░░██╔══██║░╚═══██╗░░░██║░░░██╔══╝░░██╔══██╗██╔══██║░╚═══██╗██║░░██╗██╔══╝░░██║╚████║██║░░██║ #
# ██║░░░░░██║░░██║██████╔╝░░░██║░░░███████╗██║░░██║██║░░██║██████╔╝╚█████╔╝███████╗██║░╚███║██████╔╝ #
# ╚═╝░░░░░╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝╚═════╝░░╚════╝░╚══════╝╚═╝░░╚══╝╚═════╝░ #
######################################################################################################
# Made by TimeCode @ 2024  #
#   Plugin-Version: 1.3    #
#       (14.07.2024)       #
##############################################################################################################
# If you got an error or found a bug (or if you have wishes), join my discord: https://discord.gg/V2wdDPktqc #
##############################################################################################################
# This plugin was made for the Minecraft-Versions 1.14-1.21! Using lower versions might result in problems   #
##############################################################################################################

#Change this to "false" if you want to disable this plugin
Enabled: true

#Change the InstantClimbUp options
#Enables a boost to quickly climb to the top of a structure like a ladder
#IF YOU ENABLE THIS FUNCTION IT MIGHT HAVE CONSEQUENCES
InstantClimbUp:
  #Enable this feature ("true")
  Enabled: false
  #Only works if you start climbing from the ground
  OnlyOnGround: true
  #RELEVANT ONLY IF ONLYONGROUND IS ENABLED
  #Activates the normal boost if you start climbing from halfway up
  #IMPORTANT: THIS OPTION MUST BE DISABLED ("false") IF ONLYONGROUND IS DISABLED
  DontDisableNormalBoost: true
  #Set to "false" to disable the climbing animation and climb instantly
  WithAnimation: true

#Set the blocks where you can ascend faster
Blocks:
  #Enables faster ascending on vines
  Vines: true
  #Enables faster ascending on water
  #NOTE: Not recommended for water
  Water: false
  #Enables faster ascending on ladders
  Ladders: true
  #Enables faster ascending on scaffolding (ONLY FOR MINECRAFT VERSIONS 1.14-1.19)
  Scaffolding: true
  #Enables faster ascending on extra vines (twisting, weeping) (ONLY FOR MINECRAFT VERSIONS 1.14-1.19)
  ExtraVines:
    #Enables faster ascending on twisting vines
    Twisting: true
    #Enables faster ascending on weeping vines
    Weeping: true

#Enables faster ascending only if the ladder/vine/water has a specific length
RequiredLength:
  #Enable this feature ("true")
  Enabled: false
  #Minimum length of the ladder/vine/water in blocks
  LengthInBlocks: 10

#Set worlds where players won't be able to use this feature
Blacklist:
  #Enable this feature ("true")
  Enabled: false
  #Set to "true" to use this list as a whitelist instead
  ToWhitelist: false
  #Add the world names to be blacklisted/whitelisted
  Worlds:
    - "world_the_end"
    - "world_the_nether"
    - "your_world"

#Change the settings for the boost (the speed which boosts the player up if he for example uses a ladder)
Boost:
  #Change the boost speed (DEFAULT: 4 | Do not set too high)
  Speed: 4
  #Change the delay in ticks (DEFAULT: 7 ticks) (Not recommended to change)
  #(A delay is needed to check if the player wants to climb down. Disable with Delay: 0 if you don't want this)
  #(Only change if speed is too high to climb down a ladder/vine/water)
  Delay: 10
  #Set custom speed and delay for specific blocks
  #ONLY WORKS IF THE BLOCK IS ENABLED IN THE Blocks OPTION!
  Custom:
    #Set custom speed and delay for vines
    Vines:
      #Enable custom boost ("true")
      Enabled: false
      #Custom speed
      Speed: 4
      #Custom delay
      Delay: 7
    #Set custom speed and delay for water
    Water:
      #Enable custom boost ("true")
      Enabled: false
      #Custom speed
      Speed: 4
      #Custom delay
      Delay: 7
    #Set custom speed and delay for ladders
    Ladders:
      #Enable custom boost ("true")
      Enabled: false
      #Custom speed
      Speed: 4
      #Custom delay
      Delay: 7
    #Set custom speed and delay for scaffolding
    Scaffolding:
      #Enable custom boost ("true")
      Enabled: false
      #Custom speed
      Speed: 4
      #Custom delay
      Delay: 7
    #Set custom speed and delay for extra vines
    ExtraVines:
      #Enable custom boost ("true")
      Enabled: false
      #Custom speed
      Speed: 4
      #Custom delay
      Delay: 7

#Adds the ability to climb up the ladder with one click
#THIS FUNCTION ONLY WORKS FROM THE GROUND!
#May require multiple right-clicks to activate
RightClick:
  #Enable this feature ("true")
  Enabled: false
  #Only use the left hand to trigger this action
  OnlyLeft: false
  #Also use the left hand to trigger this action (Does not work if OnlyLeft is enabled)
  AlsoLeft: true
  #Set to "true" to require SHIFT and RIGHTCLICK together to trigger this action
  WithShift: true
  #Set to "false" to disable the climbing animation and climb instantly
  WithAnimation: true

#Enable this mode to press shift to boost up instantly (e.g., a ladder) (cannot descend while holding SHIFT)
#ONLY USABLE ON LADDER/VINE/WATER! (Opposite of RightClick option)
ShiftMode:
  #Enable this feature ("true")
  Enabled: false
  #Set to "false" to disable the climbing animation and climb instantly
  WithAnimation: true

#Change all messages and sounds that are sent
#ALL EVENTS YOU CAN FIND IN THE API (see my spigot site) OR REQUEST A NEW EVENT ON MY DISCORD
#IMPORTANT: Change sound names (if using Minecraft versions 1.8-1.13) to older names (see old spigot/paper developer docs)
Events:
  #Event triggered when a player starts the climb animation
  #PLACEHOLDERS: %player% (player name), %block_name_lowercase% (block name in lowercase), %block_name_uppercase% (block name in uppercase)
  OnAscendStart:
    #Enable this feature ("true")
    Enabled: false
    #Message sent to the player
    Message: "&4&lYou've started climbing up the %block_name_lowercase%!"
    #Message displayed in the action bar
    Actionbar: "&c&lLet's climb up &e&l%player%"
    #Sound played when this event is triggered
    Sound:
      #All Sound-Names: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
      Name: "AMBIENT_SOUL_SAND_VALLEY_MOOD"
      #Sound volume
      Volume: 2
      #Sound pitch
      Pitch: 2
  #Event triggered when a player is boosted (can trigger multiple times for long climbs)
  OnAscendBoost:
    #Enable this feature ("true")
    Enabled: false
    #Message sent to the player
    Message: "&e&lYou got boosted!"
    #Message displayed in the action bar
    Actionbar: "&c&lB&e&lO&a&lO&f&lS&7&lT&f&l!"
    #Sound played when this event is triggered
    Sound:
      Name: "AMBIENT_SOUL_SAND_VALLEY_MOOD"
      Volume: 2
      Pitch: 2
  #Event triggered when the climb animation ends
  OnAscendEnd:
    #Enable this feature ("true")
    Enabled: false
    #Message sent to the player
    Message: "&4&lWOW! &e&lYou've now climbed up the ladder!"
    #Message displayed in the action bar
    Actionbar: "&a&lNice, we've reached the end &e&l%player%"
    #Sound played when this event is triggered
    Sound:
      Name: "AMBIENT_SOUL_SAND_VALLEY_MOOD"
      Volume: 2
      Pitch: 2
  #Event triggered when a player is instantly teleported to the top of a structure (e.g., ladder)
  OnInstantTeleport:
    #Enable this feature ("true")
    Enabled: false
    #Message sent to the player
    Message: "&4&lYou've been teleported to the top of the ladder!"
    #Message displayed in the action bar
    Actionbar: "&c&lWow, that was fast"
    #Sound played when this event is triggered
    Sound:
      Name: "AMBIENT_SOUL_SAND_VALLEY_MOOD"
      Volume: 2
      Pitch: 2

#Disable fast ascending for players in specific game modes
#Set the game mode to true to disable fast ascending for it
DisableForGameMode:
  Creative: false
  Survival: false
  Adventure: false

#Exclude players with specific permission from the ascending system
Exclusion:
  Enabled: false
  Permission: fasterascend.exclusion

#Set this option to "true" if the player should be stopped when he sneaks during an animation
SneakingStop: true

#Fixes a bug where descending scaffolding with SHIFT boosts you back to the top
#(Found in Minecraft Version 1.14)
#RECOMMENDED TO DISABLE THIS BUGFIX (Could affect "ShiftMode" option)
FixScaffolding: true

#Set the permission for the command /fastascend reload
Command-Permission: fastascend.reload

#"bStats is a free and open source website that helps the developer collect usage data from the plugin" (Source: bstats.org)
#Disable to stop sending automatic statistics
bStats: true

#DO NOT CHANGE THIS
#CHANGING THIS WILL BREAK THE CONFIG
config-version: 1.3
